name: Manual Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish (e.g. 1.0.0, 1.0.0-beta.1)'
        required: true
      tag:
        description: 'NPM tag (latest/beta)'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish --access public --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
